import { Robot, Survivor, Hazard, SectorRoute, MeshRelayBeacon, Sector, TacticalLog, MissionOverview } from '../types';

export const initialMissionOverview: MissionOverview = {
  missionClock: '04:18:42',
  goldenHourRemainingMinutes: 67.7 * 60, // 67.7 hours remaining of golden 72h
  overallMeshIntegrity: 86,
  activeRobotsCount: 6,
  totalRobotsCount: 6,
  survivorsFound: 4,
  survivorsExtracted: 1,
  activeHazards: 3,
  clearedRoutesCount: 4,
  aftershockRiskLevel: 'ELEVATED',
};

export const initialSectors: Sector[] = [
  {
    id: 'SEC-A',
    name: 'Sector Alpha - North Wing ER',
    code: 'SEC-A',
    bounds: { minX: 40, minY: 40, maxX: 380, maxY: 300 },
    structuralRating: 'stabilized',
    scannedPercentage: 94,
    stalenessMinutes: 3,
    activeHazardsCount: 0,
    survivorsCount: 1,
  },
  {
    id: 'SEC-B',
    name: 'Sector Beta - Main Tower Collapse',
    code: 'SEC-B',
    bounds: { minX: 420, minY: 40, maxX: 760, maxY: 300 },
    structuralRating: 'unstable',
    scannedPercentage: 68,
    stalenessMinutes: 8,
    activeHazardsCount: 2,
    survivorsCount: 2,
  },
  {
    id: 'SEC-C',
    name: 'Sector Gamma - Metro Void & Basement',
    code: 'SEC-C',
    bounds: { minX: 420, minY: 340, maxX: 760, maxY: 620 },
    structuralRating: 'critical_tilt',
    scannedPercentage: 35,
    stalenessMinutes: 19,
    activeHazardsCount: 1,
    survivorsCount: 1,
  },
  {
    id: 'SEC-D',
    name: 'Sector Delta - South Courtyard / Staging',
    code: 'SEC-D',
    bounds: { minX: 40, minY: 340, maxX: 380, maxY: 620 },
    structuralRating: 'moderate',
    scannedPercentage: 88,
    stalenessMinutes: 5,
    activeHazardsCount: 0,
    survivorsCount: 0,
  },
];

export const initialRobots: Robot[] = [
  {
    id: 'ROB-01',
    name: 'SkyEye-1',
    callsign: 'AERO-SCOUT',
    type: 'aerial_drone',
    status: 'patrol',
    commsStatus: 'connected',
    signalStrength: 96,
    latencyMs: 14,
    battery: 82,
    position: { x: 260, y: 150, z: 25, sectorId: 'SEC-A' },
    heading: 135,
    lastContactSecondsAgo: 0,
    lastKnownPosition: { x: 260, y: 150, timestamp: Date.now() },
    deadReckoningVector: { dx: 1.2, dy: 0.8, speed: 2.4 },
    sensors: ['LiDAR 360° Pointcloud', '4K Optical Zoom', 'Thermal IR (FLIR)', 'Barometric Altimeter'],
    activeSensorFeed: 'lidar',
    currentTask: 'LiDAR canopy 3D topography survey & aerial mesh anchor',
    payload: 'Ultralight RF Repeater Pods (x2)',
    storeAndForwardBacklog: 0,
    breadcrumbsPlaced: 3,
    firmwareVersion: 'v4.1.2-mesh',
  },
  {
    id: 'ROB-02',
    name: 'Vulcan-X',
    callsign: 'K9-TITAN',
    type: 'heavy_quadruped',
    status: 'patrol',
    commsStatus: 'connected',
    signalStrength: 78,
    latencyMs: 38,
    battery: 69,
    position: { x: 480, y: 180, z: 0, sectorId: 'SEC-B' },
    heading: 85,
    lastContactSecondsAgo: 2,
    lastKnownPosition: { x: 480, y: 180, timestamp: Date.now() - 2000 },
    deadReckoningVector: { dx: 0.6, dy: 0.2, speed: 1.1 },
    sensors: ['Acoustic Geophone array', '3D Flash LiDAR', 'CO2 Biosignature Sniffer', 'Stereo Depth Cam'],
    activeSensorFeed: 'flir',
    currentTask: 'Acoustic void listen sweep & rubble pile traversability testing',
    payload: 'Emergency Medical Kit + Acoustic Probe',
    storeAndForwardBacklog: 0,
    breadcrumbsPlaced: 1,
    firmwareVersion: 'v3.9.0-dynamic',
  },
  {
    id: 'ROB-03',
    name: 'Serpens-3',
    callsign: 'VOID-SNAKE',
    type: 'snake_crawler',
    status: 'disconnected', // Ghost mode showcase
    commsStatus: 'disconnected',
    signalStrength: 0,
    latencyMs: 9999,
    battery: 54,
    position: { x: 620, y: 460, z: -8, sectorId: 'SEC-C' },
    heading: 210,
    lastContactSecondsAgo: 312, // 5m 12s ago
    lastKnownPosition: { x: 590, y: 430, timestamp: Date.now() - 312000 },
    deadReckoningVector: { dx: 0.3, dy: 0.4, speed: 0.25 }, // estimated crawl trajectory
    sensors: ['Micro-Endoscopic Borescope', 'Thermal Needle Array', 'Methane/CO Spectrometer', 'Ultrasonic Micro-Sonar'],
    activeSensorFeed: 'spectrogram',
    currentTask: 'Autonomous subterranean crawl into collapsed elevator shaft void',
    payload: 'Flexible Micro-Oxygen Delivery Line',
    storeAndForwardBacklog: 42, // Store and forward queuing!
    breadcrumbsPlaced: 0,
    firmwareVersion: 'v4.0.0-subterranean',
  },
  {
    id: 'ROB-04',
    name: 'Titan-2',
    callsign: 'SHORE-ROVER',
    type: 'tracked_rover',
    status: 'relay_anchor',
    commsStatus: 'connected',
    signalStrength: 91,
    latencyMs: 22,
    battery: 88,
    position: { x: 450, y: 320, z: 0, sectorId: 'SEC-B' },
    heading: 340,
    lastContactSecondsAgo: 1,
    lastKnownPosition: { x: 450, y: 320, timestamp: Date.now() - 1000 },
    deadReckoningVector: { dx: 0, dy: 0, speed: 0 },
    sensors: ['Heavy Long-Range LiDAR', 'Structural Strain Radar', 'High-Gain 900MHz RF Mast', 'Night Vision NIR'],
    activeSensorFeed: 'optical',
    currentTask: 'Stationary High-Gain RF Mesh Bridge between Sector Alpha & Beta',
    payload: 'Hydraulic Micro-Jack & Heavy Beacon Deployer (x4)',
    storeAndForwardBacklog: 0,
    breadcrumbsPlaced: 4,
    firmwareVersion: 'v3.7.8-mast',
  },
  {
    id: 'ROB-05',
    name: 'Gecko-04',
    callsign: 'WALL-CRAWL',
    type: 'wall_climber',
    status: 'patrol',
    commsStatus: 'degraded',
    signalStrength: 44,
    latencyMs: 165,
    battery: 48,
    position: { x: 670, y: 220, z: 12, sectorId: 'SEC-B' },
    heading: 270,
    lastContactSecondsAgo: 14,
    lastKnownPosition: { x: 670, y: 220, timestamp: Date.now() - 14000 },
    deadReckoningVector: { dx: -0.1, dy: 0.1, speed: 0.1 },
    sensors: ['Laser Crack Displacement Gauge', 'Inclinometer Tilt Array', 'Micro-LiDAR', 'Thermal Camera'],
    activeSensorFeed: 'flir',
    currentTask: 'Vertical shear-wall integrity verification & aftershock risk telemetry',
    payload: 'Acoustic Displacement Sensors (x3)',
    storeAndForwardBacklog: 6,
    breadcrumbsPlaced: 1,
    firmwareVersion: 'v3.5.1-incline',
  },
  {
    id: 'ROB-06',
    name: 'Aqua-1',
    callsign: 'SUMP-PROBE',
    type: 'amphibious',
    status: 'triage_standby',
    commsStatus: 'connected',
    signalStrength: 72,
    latencyMs: 52,
    battery: 76,
    position: { x: 220, y: 470, z: -3, sectorId: 'SEC-D' },
    heading: 45,
    lastContactSecondsAgo: 4,
    lastKnownPosition: { x: 220, y: 470, timestamp: Date.now() - 4000 },
    deadReckoningVector: { dx: 0.3, dy: -0.2, speed: 0.4 },
    sensors: ['Multibeam Sonar', 'Water Conductivity Sensor', 'Submersible FLIR', 'Cavitation Mic'],
    activeSensorFeed: 'lidar',
    currentTask: 'Flooded basement utility corridor inspection & electrical hazard clearing',
    payload: 'Emergency Sump Pump Tether Line',
    storeAndForwardBacklog: 0,
    breadcrumbsPlaced: 2,
    firmwareVersion: 'v2.9.4-amphib',
  },
];

export const initialSurvivors: Survivor[] = [
  {
    id: 'SURV-01',
    label: 'Survivor #1 (Adult Male)',
    discoveredBy: 'ROB-02',
    discoveredAt: '03:42:10',
    location: { x: 530, y: 160, sector: 'Sector Beta', depthMeters: 2.1 },
    triage: 'immediate',
    confidence: 96,
    vitals: {
      heartRate: 118,
      spO2: 91,
      respirationRate: 26,
      acousticFreqHz: 180,
      thermalSigC: 36.4,
    },
    entrapmentType: 'heavy_rubble',
    hazardsNearby: ['HAZ-01 (Methane pocket 12m west)'],
    assignedRobotId: 'ROB-02',
    survivabilityWindowHours: 8.5,
    notes: 'Acoustic rhythmic tapping confirmed. Concrete slab pinning lower extremity. Oxygen tube queued.',
  },
  {
    id: 'SURV-02',
    label: 'Survivor #2 (Child)',
    discoveredBy: 'ROB-03',
    discoveredAt: '04:02:18',
    location: { x: 640, y: 480, sector: 'Sector Gamma', depthMeters: 4.8 },
    triage: 'immediate',
    confidence: 92,
    vitals: {
      heartRate: 132,
      spO2: 94,
      respirationRate: 30,
      acousticFreqHz: 340,
      thermalSigC: 37.1,
    },
    entrapmentType: 'void_space',
    hazardsNearby: ['HAZ-02 (Structural tilt 18°)'],
    assignedRobotId: 'ROB-03',
    survivabilityWindowHours: 14.0,
    notes: 'Detected via Serpens-3 acoustic borescope in elevator shaft crawlway. Conscious, responding to audio voice.',
  },
  {
    id: 'SURV-03',
    label: 'Survivor #3 (Adult Female)',
    discoveredBy: 'ROB-01',
    discoveredAt: '02:15:30',
    location: { x: 290, y: 190, sector: 'Sector Alpha', depthMeters: 0.6 },
    triage: 'delayed',
    confidence: 99,
    vitals: {
      heartRate: 84,
      spO2: 98,
      respirationRate: 18,
      acousticFreqHz: 210,
      thermalSigC: 36.8,
    },
    entrapmentType: 'surface_debris',
    hazardsNearby: [],
    survivabilityWindowHours: 36.0,
    notes: 'Stable vitals. Light dry-wall debris cleared. Extraction team en route via Corridor Alpha-1.',
  },
  {
    id: 'SURV-04',
    label: 'Survivor #4 (Unconfirmed biosignal)',
    discoveredBy: 'ROB-05',
    discoveredAt: '04:15:05',
    location: { x: 710, y: 190, sector: 'Sector Beta', depthMeters: 3.4 },
    triage: 'minor',
    confidence: 68,
    vitals: {
      heartRate: 72,
      spO2: 96,
      respirationRate: 14,
      acousticFreqHz: 95,
      thermalSigC: 35.8,
    },
    entrapmentType: 'confined_crawlway',
    hazardsNearby: ['HAZ-03 (High voltage transformer)'],
    survivabilityWindowHours: 48.0,
    notes: 'Faint intermittent thermal signature. Vulcan-X rerouted for secondary acoustic verification.',
  },
];

export const initialHazards: Hazard[] = [
  {
    id: 'HAZ-01',
    type: 'gas_leak',
    severity: 'critical',
    title: 'Methane / Mercaptan Rupture',
    location: { x: 570, y: 220, radius: 45, sector: 'Sector Beta' },
    readout: 'CH4: 520 PPM (Lower Explosive Limit Alert)',
    status: 'active',
    timestamp: '03:55:12',
  },
  {
    id: 'HAZ-02',
    type: 'structural_collapse',
    severity: 'high',
    title: 'Bearing Column Shear Rupture',
    location: { x: 610, y: 390, radius: 55, sector: 'Sector Gamma' },
    readout: 'Structural Deflection: 18.4° Tilt / 92% Yield Stress',
    status: 'active',
    timestamp: '04:08:44',
  },
  {
    id: 'HAZ-03',
    type: 'high_voltage',
    severity: 'moderate',
    title: 'Substation Transformer Feeder Short',
    location: { x: 730, y: 260, radius: 30, sector: 'Sector Beta' },
    readout: '480V Arc Flash Hazard / Ground Fault Detected',
    status: 'active',
    timestamp: '02:40:19',
  },
];

export const initialRoutes: SectorRoute[] = [
  {
    id: 'RTE-01',
    name: 'Corridor Alpha-1 (Primary Staging to ER)',
    status: 'clear',
    points: [
      { x: 120, y: 500 },
      { x: 180, y: 350 },
      { x: 240, y: 220 },
      { x: 290, y: 190 },
    ],
    widthCm: 140,
    riskScore: 8,
    description: 'Debris cleared by heavy equipment. Structural integrity 94%. Safe for human rescue stretcher.',
  },
  {
    id: 'RTE-02',
    name: 'Void Passage Beta-South',
    status: 'hazardous',
    points: [
      { x: 300, y: 200 },
      { x: 420, y: 190 },
      { x: 480, y: 180 },
      { x: 530, y: 160 },
    ],
    widthCm: 85,
    riskScore: 54,
    description: 'Constrained rubble crawlway. Passable by Quadruped & human specialist with SCBA gear.',
  },
  {
    id: 'RTE-03',
    name: 'Central Atrium Stairwell 2',
    status: 'blocked',
    points: [
      { x: 430, y: 250 },
      { x: 520, y: 270 },
      { x: 580, y: 280 },
    ],
    widthCm: 0,
    riskScore: 98,
    description: 'Pancake slab collapse. Blocked by 12-ton precast beam. Hydraulic shoring required.',
  },
  {
    id: 'RTE-04',
    name: 'Newly Charted HVAC Crawlway Gamma-3',
    status: 'newly_discovered',
    points: [
      { x: 500, y: 340 },
      { x: 550, y: 400 },
      { x: 620, y: 460 },
    ],
    widthCm: 45,
    riskScore: 32,
    discoveredByRobotId: 'ROB-03',
    description: 'Discovered by Serpens-3 snakebot. Provides direct bypass past blocked stairwell into basement void.',
  },
];

export const initialBeacons: MeshRelayBeacon[] = [
  {
    id: 'BCN-01',
    label: 'Relay Alpha-North (Mast)',
    deployedBy: 'Command Base',
    x: 200,
    y: 200,
    radius: 180,
    batteryHours: 42.5,
    uplinkId: 'BASE-SATCOM',
    status: 'active',
  },
  {
    id: 'BCN-02',
    label: 'Relay Beta-Portal',
    deployedBy: 'ROB-04',
    x: 440,
    y: 260,
    radius: 140,
    batteryHours: 19.8,
    uplinkId: 'BCN-01',
    status: 'active',
  },
  {
    id: 'BCN-03',
    label: 'Relay Gamma-Threshold',
    deployedBy: 'ROB-04',
    x: 520,
    y: 380,
    radius: 110,
    batteryHours: 18.2,
    uplinkId: 'BCN-02',
    status: 'active',
  },
];

export const initialLogs: TacticalLog[] = [
  {
    id: 'LOG-01',
    timestamp: '04:18:22',
    type: 'info',
    source: 'SYS_COORDINATOR',
    message: 'SLAM pointcloud fusion sync completed. 1,480,000 spatial voxels processed.',
  },
  {
    id: 'LOG-02',
    timestamp: '04:15:05',
    type: 'warning',
    source: 'GECKO-04',
    message: 'Intermittent biosignal detected at Sector Beta North-East wall. Confidence 68%.',
    relatedEntityId: 'SURV-04',
  },
  {
    id: 'LOG-03',
    timestamp: '04:12:30',
    type: 'emergency',
    source: 'MESH_MONITOR',
    message: 'SERPENS-3 RF link dropped entering Sub-Basement shaft. Switched to Ghost Store-and-Forward mode.',
    relatedEntityId: 'ROB-03',
  },
  {
    id: 'LOG-04',
    timestamp: '04:08:44',
    type: 'warning',
    source: 'TITAN-2',
    message: 'Structural strain sensor recorded 18.4° deflection on bearing column HAZ-02.',
    relatedEntityId: 'HAZ-02',
  },
  {
    id: 'LOG-05',
    timestamp: '04:02:18',
    type: 'emergency',
    source: 'SERPENS-3',
    message: 'LIVE SURVIVOR LOCATED in Elevator Void B-4! Vitals: 132 BPM, SpO2 94%. Immediate triage assigned.',
    relatedEntityId: 'SURV-02',
  },
  {
    id: 'LOG-06',
    timestamp: '03:55:12',
    type: 'emergency',
    source: 'VULCAN-X',
    message: 'Gas sniffer alert: Methane 520 PPM at Sector Beta Rubble Boundary HAZ-01.',
    relatedEntityId: 'HAZ-01',
  },
  {
    id: 'LOG-07',
    timestamp: '03:42:10',
    type: 'emergency',
    source: 'VULCAN-X',
    message: 'Survivor #1 acoustic tapping confirmed under 2.1m rubble slab. Triage: Immediate Red.',
    relatedEntityId: 'SURV-01',
  },
];
